### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by patrickleet** [kallqvist/rethinkdb-docker-cluster#1]
hey, this is working locally, but not when I deploy it via a stack to a Docker swarm.

Here is the command that fails, and the configuration:

```

January 18th 2018, 19:34:48.000 | Running command: /usr/bin/rethinkdb --bind all -d /data --canonical-address 10.0.0.47 10.0.11.3:29015
-- | --

  | January 18th 2018, 19:34:48.000 | Error in the command line: Unexpected positional parameter '10.0.11.3:29015' (did you forget the option name, or forget to quote a parameter list?).

  | January 18th 2018, 19:34:48.000 | Run 'rethinkdb help' for help on the command


```

```
rethink1:
    image: patrickleet/rethinkdb-cluster
    networks:
      - rethink
      - proxy
    environment:
      JOIN: rethink1
    volumes:
      - rethink1-data:/data
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 2G
      placement:
        constraints: 
          - node.role == worker
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=8080
        - com.df.serviceDomain=${RETHINK_DOMAIN:-localhost}
        - com.df.usersPassEncrypted=true
        - com.df.usersSecret=admin
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s

  rethink2:
    image: patrickleet/rethinkdb-cluster
    networks:
      - rethink
    environment:
      JOIN: rethink1
    volumes:
      - rethink2-data:/data
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 2G
      placement:
        constraints: 
          - node.role == worker
      labels:
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s


  rethink3:
    image: patrickleet/rethinkdb-cluster
    networks:
      - rethink
    environment:
      JOIN: rethink1
    volumes:
      - rethink3-data:/data
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 2G
      placement:
        constraints: 
          - node.role == worker
      labels:
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s

```

Only rethink1 has this issue, the only difference in the fork is just logging the command before running.

**Comment by patrickleet** [comment]
looks like it's because
https://github.com/kallqvist/rethinkdb-docker-cluster/blob/master/docker-entrypoint.sh#L7
returns two IP addresses

would you happen to know why, and which one to use if only one?

**Comment by kallqvist** [comment]
Yes, you're right. It was supposed to only get one IP from that line in the script.

I've never used swarm in production myself so I'm not sure why there would be two IP's for one container but what is needed for rethinkdb is that the canonical address is set to one adress that the other nodes can reach _this_ node on.

If both the IP's for node1 can be reached the same from node2 then it should be enough to just pick the first one like this directly after line 7:
`canonical_address =$(echo "$canonical_address" | awk '{ print $1 }')`

I'm also not 100% sure how the docker swarm networking is supposed to work but if it's possible to have port 29015 listening on the _host_ IP and set canonical IP to that instead of some bridged/tunneled networking rethinkdb will possibly get better performance.

Do you know if any of those addresses is the one that the host machine is using or are both docker IPs?

**Comment by patrickleet** [comment]
Hey turns out this is easier now - rethink just ignores the join if it is
itself.

Can share stack if you’re interested

**Comment by lagden** [comment]
@patrickleet 

Share, please!

My approach is a little bit different...

---

**docker-entrypoint.sh**
```bash
#!/bin/bash

IFS=';'; dbHostsArray=($DBCLUSTERHOSTS); unset IFS;
joinString=" "

for dbHost in ${dbHostsArray[*]}
do
	hostExists=`getent hosts $dbHost`
	if [ ! -z "$hostExists" ]; then
		joinString="$joinString --join $dbHost"
	fi
done

rethinkdb $joinString $RETHINKARGS
```

**Dockerfile**
```Dockerfile
FROM rethinkdb:2.3.6
LABEL maintainer="docker@lagden.in"

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# checking for empty command in entrypoint.sh to allow runtime override
CMD [""]
```

**docker-compose.yml**
```yaml
  #...

  rdb1:
    build: ./
    image: rdb:dev
    environment:
      - "DBCLUSTERHOSTS=rdb2;rdb3"
      - "RETHINKARGS=--server-tag primary --server-name rdb1 --bind all"
    hostname: rdb1
    networks:
      - rethink-net
    ports:
      - 8081:8080
    volumes:
      - db-data-rdb1:/data

  rdb2:
    image: rdb:dev
    environment:
      - "DBCLUSTERHOSTS=rdb1;rdb3"
      - "RETHINKARGS=--server-tag primary --server-name rdb2 --bind all"
    hostname: rdb2
    networks:
      - rethink-net
    ports:
      - 8082:8080
    volumes:
      - db-data-rdb2:/data

  rdb3:
    image: rdb:dev
    environment:
      - "DBCLUSTERHOSTS=rdb1;rdb2"
      - "RETHINKARGS=--server-tag primary --server-name rdb3 --bind all"
    hostname: rdb3
    networks:
      - rethink-net
    ports:
      - 8083:8080
    volumes:
      - db-data-rdb3:/data

  #...
```

**Comment by patrickleet** [comment]
oh I like this, thanks for sharing!

This is a bit cleaner than mine 👍 

Basically I figured out that if you deploy to a stack with the command specified, it will eventually all start up, because if the dependent instance isn't ready, it will just fail and reschedule.

```
version: '3.3'

networks:

  proxy:
    external: true

  rethink:
    external: true

services:

  primary:
    image: rethinkdb:2
    networks:
      - rethink
    volumes:
      - primary-data:/data
    command: ["rethinkdb", "--bind", "all", "--no-http-admin", "--join", "primary"]
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
      placement:
        constraints: 
          - node.role == worker

  ui:
    image: rethinkdb:2
    networks:
      - proxy
    volumes:
      - ui-data:/data
    command: ["rethinkdb", "--bind", "all", "--join", "primary"]
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
      placement:
        constraints: 
          - node.role == worker

  write:
    image: rethinkdb:2
    networks:
      - rethink
    volumes:
      - write-data:/data
    command: ["rethinkdb", "--bind", "all", "--no-http-admin", "--join", "primary"]
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
      placement:
        constraints: 
          - node.role == worker

volumes:

  primary-data:
    driver: cloudstor:aws
    external: false

  ui-data:
    driver: cloudstor:aws
    external: false
  
  write-data:
    driver: cloudstor:aws
    external: false
```

**Comment by kallqvist** [comment]
This line was supposed to ensure that a rethinkdb node never tries to connect to it's own IP.
https://github.com/kallqvist/rethinkdb-docker-cluster/blob/2b725959b5b20e73f446119c350739ac5f0b1241/docker-entrypoint.sh#L16

If both "hostname -i" and "getent hosts rdb1" return IP's from the same series nothing else should have to be passed to rethink, not entirely sure why it didn't work for you guys.

I'm running this image in staging (it's a rancher environment) using only dns name for clustering and host network mode and this is all docker-compose I ever had to setup for that:
```
version: '2'
services:
  rethinkdb:
    image: kallqvist/rethinkdb-cluster
    environment:
      JOIN: rethinkdb
    network_mode: host
    volumes:
    - /mnt/xvdb/server_data/rethinkdb:/data
    ports:
    - 28015:28015/tcp
    - 8080:8080/tcp
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
```
